# Generated by Django 4.2.16 on 2024-11-18 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('frontend', 'Frontend Service'), ('backend', 'Backend Service'), ('ml_pipeline', 'ML Pipeline'), ('data_fetcher', 'Data Fetcher')], max_length=50, unique=True)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('last_check', models.DateTimeField(null=True)),
                ('last_status_change', models.DateTimeField(null=True)),
                ('endpoint', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type', models.CharField(choices=[('data_fetch', 'Data Fetching'), ('data_process', 'Data Processing'), ('model_train', 'Model Training'), ('prediction', 'Prediction Generation')], max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['pipeline_type', 'status', 'start_time'], name='base_pipeli_pipelin_d25a93_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.service')),
            ],
            options={
                'indexes': [models.Index(fields=['service', 'metric_type', 'timestamp'], name='base_metric_service_9d84db_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledged_at', models.DateTimeField(null=True)),
                ('pipeline_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.pipelinerun')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.service')),
            ],
            options={
                'indexes': [models.Index(fields=['severity', 'timestamp', 'acknowledged'], name='base_alert_severit_e41905_idx')],
            },
        ),
    ]
